# Generated by Django 5.2.7 on 2025-10-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trade_close_date_trade_created_at_trade_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
    ]
