# Generated by Django 5.2.7 on 2025-10-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5),
        ),
        migrations.AlterField(
            model_name='trade',
            name='screenshot',
            field=models.URLField(blank=True, help_text='Optional link to chart image'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=100),
        ),
    ]
