# Generated by Django 5.2.7 on 2025-10-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_unique_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cryptoasset',
            new_name='core_crypto_user_id_2bf443_idx',
            old_name='core_crypto_user_sy_idx',
        ),
    ]
