# Generated by Django 5.2.7 on 2026-04-20 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_default_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='asset_type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('stock', 'Stock')], default='crypto', max_length=10),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='market',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='cryptoasset',
            index=models.Index(fields=['user', 'asset_type'], name='core_crypto_user_id_a0445b_idx'),
        ),
    ]
