# k8s/04-analytics-service.yaml
# Analytics FastAPI Microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: fibonacci
  labels:
    app: analytics-service
    tier: backend
spec:
  replicas: 2  # Multiple replicas for scalability and reliability
  selector:
    matchLabels:
      app: analytics-service
  strategy:
    type: RollingUpdate  # Enables rollout and rollback
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: analytics-service
        tier: backend
        version: v1
    spec:
      containers:
      - name: analytics
        image: fibonacci-analytics-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fibonacci-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: fibonacci
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: analytics-service
