# k8s/05-portfolio-service.yaml
# Portfolio FastAPI Microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
  namespace: fibonacci
  labels:
    app: portfolio-service
    tier: backend
spec:
  replicas: 2  # Multiple replicas for scalability and reliability
  selector:
    matchLabels:
      app: portfolio-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: portfolio-service
        tier: backend
        version: v1
    spec:
      containers:
      - name: portfolio
        image: fibonacci-portfolio-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fibonacci-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: DB_PORT
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: fibonacci-config
              key: CORS_ORIGINS
        - name: COINGECKO_API_KEY
          valueFrom:
            secretKeyRef:
              name: fibonacci-secret
              key: COINGECKO_API_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: fibonacci
  labels:
    app: portfolio-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: portfolio-service
