# k8s/07-frontend.yaml
# Frontend React + Nginx Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fibonacci
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 2  # Multiple replicas for high availability
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: fibonacci-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fibonacci
  labels:
    app: frontend
spec:
  type: LoadBalancer  # LoadBalancer for external access
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend
