#!/bin/bash
# generate_secret.sh — generate k8s/02-secret.yaml from env vars or random defaults
#
# Reads sensitive config from the environment. Falls back to randomly generated
# values when unset. The resulting manifest is gitignored — never commit the
# rendered file.
#
# Usage:
#   ./k8s/generate_secret.sh
#   DB_PASSWORD=... SECRET_KEY=... COINGECKO_API_KEY=... ./k8s/generate_secret.sh

set -e

cd "$(dirname "$0")/.."

TEMPLATE="k8s/02-secret.yaml.example"
OUTPUT="k8s/02-secret.yaml"

if [ ! -f "$TEMPLATE" ]; then
    echo "❌ Template not found: $TEMPLATE"
    exit 1
fi

rand_hex() {
    openssl rand -hex "$1" 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex($1))"
}

DB_PASSWORD="${DB_PASSWORD:-$(rand_hex 24)}"
SECRET_KEY="${SECRET_KEY:-$(rand_hex 48)}"
COINGECKO_API_KEY="${COINGECKO_API_KEY:-}"

cat > "$OUTPUT" <<EOF
# k8s/02-secret.yaml
# GENERATED by k8s/generate_secret.sh — do not commit.
# Regenerate with fresh values by re-running the script.
apiVersion: v1
kind: Secret
metadata:
  name: fibonacci-secret
  namespace: fibonacci
type: Opaque
stringData:
  DB_PASSWORD: "${DB_PASSWORD}"
  SECRET_KEY: "${SECRET_KEY}"
  COINGECKO_API_KEY: "${COINGECKO_API_KEY}"
EOF

chmod 600 "$OUTPUT"

echo "✅ Wrote $OUTPUT (mode 600)"
echo "   DB_PASSWORD length:  ${#DB_PASSWORD}"
echo "   SECRET_KEY length:   ${#SECRET_KEY}"
if [ -z "$COINGECKO_API_KEY" ]; then
    echo "   COINGECKO_API_KEY:   (empty — set COINGECKO_API_KEY env var to populate)"
else
    echo "   COINGECKO_API_KEY:   set"
fi
